# permissions for end users to view podautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podautoscaler-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: podautoscaler
    app.kubernetes.io/part-of: podautoscaler
    app.kubernetes.io/managed-by: kustomize
  name: podautoscaler-viewer-role
rules:
- apiGroups:
  - webapp.my.domain
  resources:
  - podautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - podautoscalers/status
  verbs:
  - get
